export const MOROCCAN_CITIES = [
    'Agadir',
    'Al Hoceima',
    'Béni Mellal',
    'Casablanca',
    'Chefchaouen',
    'Dakhla',
    'El Jadida',
    'Errachidia',
    'Essaouira',
    'Fès',
    'Guelmim',
    'Ifrane',
    'Kénitra',
    'Khénifra',
    'Khouribga',
    'Laâyoune',
    'Larache',
    'Marrakech',
    'Meknès',
    'Mohammédia',
    'Nador',
    'Ouarzazate',
    'Oujda',
    'Rabat',
    'Safi',
    'Salé',
    'Settat',
    'Tanger',
    'Taroudant',
    'Taza',
    'Tétouan',
    'Tiznit',
].sort((a, b) => a.localeCompare(b));
